### ISSUE TITLE
Connect to multiple cameras in a single process

### ISSUE THREAD

**Issue by llschloesser** [FLIR/BosonLinuxSDK#2]
There are a handful of static global variables in play here. Are there plans to update this code to allow connecting to multiple cameras in a single process?

Perhaps consider a  C++ API?

**Comment by llschloesser** [comment]
Thanks for the response, you guys rock, especially at creating minimally functional APIs!

**Comment by andrespm** [comment]
This code , and the corresponding BosonUSB are intended for demo only and for one camera.
Just to show that the interfaces are easy from Linux.

**Comment by llschloesser** [comment]
Since the interfaces are "easy", please extend to support multiple cameras. Didn't you guys buy Point Grey? They make non-demo SDKs, maybe ask those guys to take a stab turning this into an actual SDK.

**Comment by andrespm** [comment]
It is sad to see that when you open something that before wasn't available, thinking that may help people on Linux, you get this kind of messages. But taking it from the positive side, thanks for your comment, it will help us to get better.

**Comment by llschloesser** [comment]
I apologize if the snark is over the top, I don’t intend to demean individuals. From my perspective FLIR is a corporation selling $5k cameras for years with very limited software support. As an end user it is disappointing and frustrating. I shouldn’t have to totally rework an inscrutable SDK for the same system it was targeted for.

**Comment by andrespm** [comment]
Have you tried the rawBoson project? it gives you just the basic to talk with the camera... perhaps easier to build from there. It is not an SDK, it implements the protocol, won't save you time, but perhaps easier for your application. 
I hope and believe that FLIR will get better from the user perspective ( I understand your point ).

**Comment by andrespm** [comment]
SDK team are aware now of this requested feature.  It is now part of their normal backlog of features. 
Thanks,
