### ISSUE TITLE
Does this assume a USB C adapter for the Boson 320/640?

### ISSUE THREAD

**Issue by drjasonharrison-vp-eio** [FLIR/BosonLinuxSDK#3]
It is not clear from the readme if this sample assumes a UBC C adapter or other connection to the Boson 320/640.

**Comment by andrespm** [comment]
You are right, there is a Boson USB adapter.
We are assuming in this example that you have that adapter.
It gives you a USB connection, that gives you the typical /dev/ttyACM0 for command&Control , and /dev/videoX for 16 bits or 8 bits video.

**Comment by andrespm** [comment]
This is the LINK to the VPC module 
https://www.flir.com/products/421-0061-00_vpc/
