### ISSUE TITLE
Does the camera reply if the CRC is invalid?

### ISSUE THREAD

**Issue by jveitchmichaelis** [FLIR/BosonLinuxSDK#5]
Hi,

I've been porting the serial protocol over to Python. I've managed to get the camera to respond, but only if the CRC is correct. For example, the byte sequence for reading the camera serial number (note, dummy checksum):

`b'\x8e\x00\x00\x00\x00\x00\x00\x05\x00\x02\xff\xff\xff\xff\x00\x00\xae')`

elicits a timeout, whereas:

`b'\x8e\x00\x00\x00\x00\x00\x00\x05\x00\x02\xff\xff\xff\xff\xea(\xae')`

returns:

`b'\x8e\x00\x00\x00\x00\x00\x00\x05\x00\x02\x00\x00\x00\x00\x00\x00*~\x8a|\xae'`

as expected.

Is this always the case, given that there's a [typedef ](https://github.com/FLIR/BosonLinuxSDK/blob/5df5e209771e89baaf6cc176ce1a3121e2689642/ClientFiles_C/ReturnCodes.h#L57)for an incorrect checksum? Is that a return code from the camera, or is that just for the client code to flag if there's an invalid checksum in the return frame?

Similarly the code in the SDK [does some work to escape the start and end frame markers](https://github.com/FLIR/BosonLinuxSDK/blob/5df5e209771e89baaf6cc176ce1a3121e2689642/EmulatorFiles/HostBinaryProtocol.c#L627) if they appear in the packet, but the [rawboson ](https://github.com/FLIR/rawBoson)library doesn't. Is this simply a rare occurrence, and the raw library is getting away without it,  or is it necessary to communicate with the camera?

I'm guessing it's just to add some robustness, because without a payload length in the frame header, you can have situations where the escape marker has to be escaped _ad infinitum_.

Thanks!

**Comment by andrespm** [comment]
Regarding 2:  "Bitstuffing"
RawBoson has the functions to do that, in fact is trying to do it, but we think is failing there. There was another issue reported and sounds it is related to this one.  We are checking both.

**Comment by andrespm** [comment]
We found an issue in the Bitstuffing function. It has been fixed in DEVELOP BRANCH and should fix any CRC issue with previous version.
